apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: "az-app-filter-policy"
spec:
  rules:
    - host: "*"
      path: "/users/me"
      filters:
        - name: "az-app-jwt-filter"
    - host: "*"
      path: "/messages"
      filters:
        - name: "az-app-jwt-filter"
    - host: "*"
      path: "/messages/*"
      filters:
        - name: "az-app-jwt-filter"