apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-auth-chart.fullname" . }}
  labels:
    {{- include "app-auth-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "app-auth-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "app-auth-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app-auth-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-psql
          image: busybox
          env:
            - name: AZ_OTUS_DB_PATH
              valueFrom:
                configMapKeyRef:
                  key: MARIADB_PATH
                  name: {{ include "app-auth-chart.fullname" . }}
          command: ["sh", "-c", "until nc -zv $AZ_OTUS_DB_PATH; do echo waiting for mysql; sleep 2; done;"]
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AZ_OTUS_AUTH_DATABASE
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URI
                  name: {{ include "app-auth-chart.fullname" . }}
            - name: AZ_OTUS_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  key: SECRET
                  name: {{ include "app-auth-chart.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
