replicaCount: 2

image:
  repository: agzhur/az-otus-homework-go-app
  pullPolicy: Always
  tag: "1.11"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
cacheEnabled: true

serviceAccount:
  create: false

service:
  type: NodePort
  port: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths:
        - /otusapp
  tls: []

metrics:
  serviceMonitor:
    enabled: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

redis:
  path: "redis-master"
  port: "6379"

mariadb:
  label: mariadb
  service:
    port: "3306"
  db:
    name: az_db
    user: az_otus
    password: azPassword
